# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import glossary_pb2 as glossary__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in glossary_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GlossaryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpsertTerm = channel.unary_unary(
                '/vkr.glossary.GlossaryService/UpsertTerm',
                request_serializer=glossary__pb2.UpsertTermRequest.SerializeToString,
                response_deserializer=glossary__pb2.UpsertTermResponse.FromString,
                _registered_method=True)
        self.GetTerm = channel.unary_unary(
                '/vkr.glossary.GlossaryService/GetTerm',
                request_serializer=glossary__pb2.TermId.SerializeToString,
                response_deserializer=glossary__pb2.GetTermResponse.FromString,
                _registered_method=True)
        self.DeleteTerm = channel.unary_unary(
                '/vkr.glossary.GlossaryService/DeleteTerm',
                request_serializer=glossary__pb2.TermId.SerializeToString,
                response_deserializer=glossary__pb2.DeleteTermResponse.FromString,
                _registered_method=True)
        self.ListTerms = channel.unary_unary(
                '/vkr.glossary.GlossaryService/ListTerms',
                request_serializer=glossary__pb2.ListTermsRequest.SerializeToString,
                response_deserializer=glossary__pb2.ListTermsResponse.FromString,
                _registered_method=True)
        self.SearchTerms = channel.unary_unary(
                '/vkr.glossary.GlossaryService/SearchTerms',
                request_serializer=glossary__pb2.SearchTermsRequest.SerializeToString,
                response_deserializer=glossary__pb2.SearchTermsResponse.FromString,
                _registered_method=True)
        self.GetGraph = channel.unary_unary(
                '/vkr.glossary.GlossaryService/GetGraph',
                request_serializer=glossary__pb2.GetGraphRequest.SerializeToString,
                response_deserializer=glossary__pb2.GetGraphResponse.FromString,
                _registered_method=True)


class GlossaryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpsertTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTerms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchTerms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlossaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpsertTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertTerm,
                    request_deserializer=glossary__pb2.UpsertTermRequest.FromString,
                    response_serializer=glossary__pb2.UpsertTermResponse.SerializeToString,
            ),
            'GetTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTerm,
                    request_deserializer=glossary__pb2.TermId.FromString,
                    response_serializer=glossary__pb2.GetTermResponse.SerializeToString,
            ),
            'DeleteTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTerm,
                    request_deserializer=glossary__pb2.TermId.FromString,
                    response_serializer=glossary__pb2.DeleteTermResponse.SerializeToString,
            ),
            'ListTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTerms,
                    request_deserializer=glossary__pb2.ListTermsRequest.FromString,
                    response_serializer=glossary__pb2.ListTermsResponse.SerializeToString,
            ),
            'SearchTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchTerms,
                    request_deserializer=glossary__pb2.SearchTermsRequest.FromString,
                    response_serializer=glossary__pb2.SearchTermsResponse.SerializeToString,
            ),
            'GetGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGraph,
                    request_deserializer=glossary__pb2.GetGraphRequest.FromString,
                    response_serializer=glossary__pb2.GetGraphResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vkr.glossary.GlossaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vkr.glossary.GlossaryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GlossaryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpsertTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vkr.glossary.GlossaryService/UpsertTerm',
            glossary__pb2.UpsertTermRequest.SerializeToString,
            glossary__pb2.UpsertTermResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vkr.glossary.GlossaryService/GetTerm',
            glossary__pb2.TermId.SerializeToString,
            glossary__pb2.GetTermResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vkr.glossary.GlossaryService/DeleteTerm',
            glossary__pb2.TermId.SerializeToString,
            glossary__pb2.DeleteTermResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vkr.glossary.GlossaryService/ListTerms',
            glossary__pb2.ListTermsRequest.SerializeToString,
            glossary__pb2.ListTermsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vkr.glossary.GlossaryService/SearchTerms',
            glossary__pb2.SearchTermsRequest.SerializeToString,
            glossary__pb2.SearchTermsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vkr.glossary.GlossaryService/GetGraph',
            glossary__pb2.GetGraphRequest.SerializeToString,
            glossary__pb2.GetGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
